package pojos;
// Generated 17/02/2019, 2:18:41 p.m. by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private String identificacion;
     private String nombres;
     private String apellidos;
     private int edad;
     private String idTutor;
     private int idGrado;

    public Alumno() {
    }

    public Alumno(String identificacion, String nombres, String apellidos, int edad, String idTutor, int idGrado) {
       this.identificacion = identificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.edad = edad;
       this.idTutor = idTutor;
       this.idGrado = idGrado;
    }
   
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getIdTutor() {
        return this.idTutor;
    }
    
    public void setIdTutor(String idTutor) {
        this.idTutor = idTutor;
    }
    public int getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(int idGrado) {
        this.idGrado = idGrado;
    }




}


