package pojos;
// Generated 17/02/2019, 2:18:41 p.m. by Hibernate Tools 4.3.1



/**
 * MateriaPorPeriodo generated by hbm2java
 */
public class MateriaPorPeriodo  implements java.io.Serializable {


     private MateriaPorPeriodoId id;

    public MateriaPorPeriodo() {
    }

    public MateriaPorPeriodo(MateriaPorPeriodoId id) {
       this.id = id;
    }
   
    public MateriaPorPeriodoId getId() {
        return this.id;
    }
    
    public void setId(MateriaPorPeriodoId id) {
        this.id = id;
    }




}


