package pojos;
// Generated 17/02/2019, 2:18:41 p.m. by Hibernate Tools 4.3.1



/**
 * NotaId generated by hbm2java
 */
public class NotaId  implements java.io.Serializable {


     private String idAlumno;
     private int idMateria;

    public NotaId() {
    }

    public NotaId(String idAlumno, int idMateria) {
       this.idAlumno = idAlumno;
       this.idMateria = idMateria;
    }
   
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotaId) ) return false;
		 NotaId castOther = ( NotaId ) other; 
         
		 return ( (this.getIdAlumno()==castOther.getIdAlumno()) || ( this.getIdAlumno()!=null && castOther.getIdAlumno()!=null && this.getIdAlumno().equals(castOther.getIdAlumno()) ) )
 && (this.getIdMateria()==castOther.getIdMateria());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdAlumno() == null ? 0 : this.getIdAlumno().hashCode() );
         result = 37 * result + this.getIdMateria();
         return result;
   }   


}


