package pojos;
// Generated 17/02/2019, 2:18:41 p.m. by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private int id;
     private Date fechaInicio;
     private Date fechaFinal;

    public Periodo() {
    }

    public Periodo(int id, Date fechaInicio, Date fechaFinal) {
       this.id = id;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }




}


