package pojos;
// Generated 17/02/2019, 2:18:41 p.m. by Hibernate Tools 4.3.1



/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


     private String identificacion;
     private String nombres;
     private String apellidos;
     private String correo;
     private String telefono;

    public Tutor() {
    }

    public Tutor(String identificacion, String nombres, String apellidos, String correo, String telefono) {
       this.identificacion = identificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.correo = correo;
       this.telefono = telefono;
    }
   
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


